#!/usr/bin/env bash
#### Yumi-YMS-Manager module
####
#### https://github.com/Yumi-Lab/Yumi-YMS-Manager
#### Klipper extra for multi-color visual rendering (YMS)
####
#### This module MUST run after klipper, mainsail, and moonraker modules.

# shellcheck enable=require-variable-braces
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing Yumi-YMS-Manager ..."

## Clone repo
pushd "/home/${BASE_USER}" &>/dev/null || exit 1
sudo -u "${BASE_USER}" \
    git clone --depth 1 -b "${YMS_MANAGER_REPO_BRANCH}" "${YMS_MANAGER_REPO_SHIP}" "${YMS_MANAGER_DIR}"
git config --global --add safe.directory "${YMS_MANAGER_DIR}"
chown -R "${BASE_USER}:${BASE_USER}" "${YMS_MANAGER_DIR}"

## Run installer (creates symlinks to Klipper extras + patches Mainsail + adds Moonraker update manager)
sudo -u "${BASE_USER}" bash -c "cd ${YMS_MANAGER_DIR} && ./install.sh"

popd &>/dev/null || exit 1

echo_green "Installing Yumi-YMS-Manager ... [DONE]"
