#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Install MCU RPI..."

# Deploy klipper_linux.config for firstboot compilation
unpack /filesystem/home/"${BASE_USER}" /home/"${BASE_USER}" "${BASE_USER}"

# Install klipper-mcu systemd service
cd /home/pi/klipper/
cp /home/pi/klipper/scripts/klipper-mcu.service /etc/systemd/system/
# Remove -r (realtime scheduling) flag — not supported on Armbian Trixie kernel 6.18+
sed -i 's|klipper_mcu -r |klipper_mcu |' /etc/systemd/system/klipper-mcu.service
systemctl_if_exists enable klipper-mcu.service

# klipper_linux.config is deployed via filesystem overlay to /home/pi/
# Compilation of the Linux MCU happens at first boot (firstboot wizard)

# Add pi to tty group for serial access
usermod -a -G tty pi

echo_green "Install MCU RPI... [DONE]"

