#!/usr/bin/env bash
# YumiOS-Klipper-V2 — SmartPi ONE (armhf)
# shellcheck enable=require-variable-braces
# shellcheck disable=SC2034

# Image base (SmartPi-armbian)
DOWNLOAD_URL_CHECKSUM="https://github.com/Yumi-Lab/SmartPi-armbian/releases/download/v1.7.0/Yumi-smartpi1-bookworm-debian12-server-2026-04-23-0753.img.xz.sha256"
DOWNLOAD_URL_IMAGE="https://github.com/Yumi-Lab/SmartPi-armbian/releases/download/v1.7.0/Yumi-smartpi1-bookworm-debian12-server-2026-04-23-0753.img.xz"

# Disk size (MB)
BASE_IMAGE_ENLARGEROOT=6000

# Architecture
BASE_ARCH="armhf"

# OS naming for image file naming convention
BASE_OS_CODENAME="bookworm"
BASE_OS_VERSION="debian12"

# Modules — YumiOS Klipper stack for SmartPi One
MODULES="base(udev_fix,armbian(armbian_net,yumios,klipper,is_req_preinstall,moonraker,mainsail,timelapse,klipperscreen,crowsnest,usb-automount,cpu_governor,mcu-rpi,tmc-autotune,smartpad))"

export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_OS_CODENAME
export BASE_OS_VERSION
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
export MODULES
