#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


# Install TMC AUTOTUNE for GCODES
echo_green "Install TMC Autotune..."
echo_green "Install TMC Autotune git clone..."
pushd "/home/${BASE_USER}" &>/dev/null || exit 1
sudo -u "${BASE_USER}" git clone https://github.com/Yumi-Lab/klipper_tmc_autotune.git

## install.sh cannot run in chroot (checks systemctl for klipper.service)
## Do manually what it does: symlink extensions into klippy/extras/
KLIPPER_EXTRAS="/home/${BASE_USER}/klipper/klippy/extras"
TMC_DIR="/home/${BASE_USER}/klipper_tmc_autotune"
ln -srfn "${TMC_DIR}/autotune_tmc.py" "${KLIPPER_EXTRAS}/autotune_tmc.py"
ln -srfn "${TMC_DIR}/motor_constants.py" "${KLIPPER_EXTRAS}/motor_constants.py"
ln -srfn "${TMC_DIR}/motor_database.cfg" "${KLIPPER_EXTRAS}/motor_database.cfg"

git config --global --add safe.directory "${TMC_DIR}"
chown -R "${BASE_USER}:${BASE_USER}" "${TMC_DIR}"
popd &>/dev/null || exit 1
echo_green "Install TMC Autotune... [DONE]"

