#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


# Install TMC AUTOTUNE for GCODES
echo_green "Install TMC Autotune..."
echo_green "Install TMC Autotune git clone..."
pushd /home/pi &>/dev/null || exit 1
sudo -u "${BASE_USER}" git clone https://github.com/Yumi-Lab/klipper_tmc_autotune.git
pushd klipper_tmc_autotune &>/dev/null || exit 1
chmod +x install.sh
sudo -u "${BASE_USER}" ./install.sh
git config --global --add safe.directory /home/pi/klipper_tmc_autotune
git reset --hard HEAD
popd &>/dev/null || exit 1
chown -R "${BASE_USER}:${BASE_USER}" /home/pi/klipper_tmc_autotune
popd &>/dev/null || exit 1
echo_green "Install TMC Autotune... [DONE]"

