#!/usr/bin/env bash
# shellcheck disable=all
#### SmartPad / SmartPi ONE — Yumi-Lab customizations

[[ -n "$SMARTPAD_CONFIG_TXT_FILE" ]] || SMARTPAD_CONFIG_TXT_FILE="/boot/armbianEnv.txt"
[[ -n "$SMARTPAD_PLYMOUTH_REPO" ]] || SMARTPAD_PLYMOUTH_REPO="https://github.com/Yumi-Lab/plymouth-themes.git"
[[ -n "$SMARTPAD_PLYMOUTH_THEME" ]] || SMARTPAD_PLYMOUTH_THEME="tech_b"
[[ -n "$SMARTPAD_PLYMOUTH_PACK" ]] || SMARTPAD_PLYMOUTH_PACK="pack_4"
[[ -n "$SMARTPAD_DEPS" ]] || SMARTPAD_DEPS="plymouth dialog v4l-utils console-setup keyboard-configuration kbd"